logging:
  level:
    org:
      springframework:
        web: error
    root: error
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:org/example/**/mapper/*.xml

server:
  port: 8200
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: service-other
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
#    primary:
#      #数据库url，如果是单例, key应为url
#      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password:
#    secondary:
#      jdbc-url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password:
#  redis:
#    database: 0 # Redis 数据库索引（默认为 0）
#    host: localhost # Redis 服务器地址
#    port: 6379 # Redis 服务器连接端口
#    password:  # Redis 服务器连接密码（默认为空）
#    timeout:  5000  # 连接超时，单位ms
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 8 # 连接池中的最大空闲连接 默认 8
#        min-idle: 0 # 连接池中的最小空闲连接 默认 0

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 50
    packages:
      trust-all: true   #是否信任所有包，信任后所有包内的对象均可序列化传输
#  jms:
#    #开启activemq发布订阅模式,现为了同时支持两种模式，改为代码实现
#    pub-sub-domain: true
