logging:
  level:
    org:
      springframework:
        web: error
    root: error
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:org/example/**/mapper/*.xml

server:
  port: 8300
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: service-resource

# MinIo文件服务器
minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: admin123456