logging:
  level:
    org:
      springframework:
        web: error
    root: error

server:
  port: 8300
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: service-resource

# MinIo文件服务器
minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: admin123456