#server:
#  port: 8011
#  servlet:
#    context-path:
#
#logging:
#  level:
#    org:
#      springframework:
#        web: error
#    root: error
#
#spring:
#  application:
#    name: service-shop
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 172.25.220.145:8848
##eureka:
##  client:
##    service-url:
##      defaultZone: http://localhost:8761/eureka/eureka/

