logging:
  level:
    org:
      springframework:
        web: error
    root: error
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8010
  servlet:
    #    context-path: /uaa
    session:
      #session失效时间，最短1分钟
      timeout: 30
      cookie:
        #浏览器脚本不能访问cookie
        http-only: true
        #仅通过https发送cookie
        secure: false
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: service-oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/eureka/